"use client";

import type { BackendAlert, DeviceEntry } from "./types";

type Props = {
  devices: DeviceEntry[];
  alerts: BackendAlert[];
};

/** Fault notifications generated by the monitoring workflow. */
export function AlertsPanel({ devices, alerts }: Props) {
  const active = devices.filter((d) => d.status !== "Online");
  return (
    <section className="section-panel">
      <div className="section-panel-inner wide-panel">
        <span className="overline">NETWORK / ALERTS</span>
        <h1>Fault notifications</h1>
        <p>Events generated by the monitoring workflow and dispatched through the configured email node.</p>
        {alerts.map((alert) => <article className="dashboard-integration-card" key={alert.id}><div className="dashboard-integration-icon">!</div><div><strong>{alert.deviceName} — {alert.status} ({alert.severity})</strong><small>{alert.ipAddress} · {alert.createdAt.slice(0, 19).replace("T", " ")}</small><p>{alert.summary}</p><p>Email: {alert.emailStatus}</p></div></article>)}
        {active.map((d) => <article className="dashboard-integration-card" key={d.ip}><div className="dashboard-integration-icon">!</div><div><strong>{d.name} — {d.status}</strong><small>{d.ip}</small><p>Workflow: Network Fault → AI Message → Gmail</p></div></article>)}
        {!active.length && !alerts.length && <p>No active faults.</p>}
      </div>
    </section>
  );
}
