import { boolean, index, int, json, mysqlTable, text, timestamp, varchar } from "drizzle-orm/mysql-core";

const timestamps = { createdAt: timestamp("created_at").notNull(), updatedAt: timestamp("updated_at").notNull() };
export const organizations = mysqlTable("organizations", { id: varchar("id", { length: 36 }).primaryKey(), name: varchar("name", { length: 255 }).notNull(), slug: varchar("slug", { length: 255 }).notNull().unique(), ...timestamps });
export const users = mysqlTable("users", { id: varchar("id", { length: 36 }).primaryKey(), email: varchar("email", { length: 255 }).notNull().unique(), name: varchar("name", { length: 255 }).notNull(), ...timestamps });
export const memberships = mysqlTable("memberships", { id: varchar("id", { length: 36 }).primaryKey(), organizationId: varchar("organization_id", { length: 36 }).notNull(), userId: varchar("user_id", { length: 36 }).notNull(), role: varchar("role", { length: 32 }).notNull().default("viewer"), ...timestamps }, (table) => ({ organizationIdx: index("memberships_organization_idx").on(table.organizationId) }));
export const resources = mysqlTable("resources", { id: varchar("id", { length: 36 }).primaryKey(), organizationId: varchar("organization_id", { length: 36 }).notNull(), name: varchar("name", { length: 255 }).notNull(), kind: varchar("kind", { length: 32 }).notNull(), config: json("config").notNull(), ...timestamps });
export const workflows = mysqlTable("workflows", { id: varchar("id", { length: 36 }).primaryKey(), organizationId: varchar("organization_id", { length: 36 }).notNull(), name: varchar("name", { length: 255 }).notNull(), description: text("description").notNull(), triggerEvent: varchar("trigger_event", { length: 255 }).notNull(), enabled: boolean("enabled").notNull().default(true), ...timestamps });
export const workflowNodes = mysqlTable("workflow_nodes", { id: varchar("id", { length: 36 }).primaryKey(), workflowId: varchar("workflow_id", { length: 36 }).notNull(), kind: varchar("kind", { length: 32 }).notNull(), name: varchar("name", { length: 255 }).notNull(), capability: varchar("capability", { length: 255 }), config: json("config"), position: int("position").notNull().default(0) });
export const events = mysqlTable("events", { id: varchar("id", { length: 36 }).primaryKey(), organizationId: varchar("organization_id", { length: 36 }).notNull(), type: varchar("type", { length: 255 }).notNull(), source: varchar("source", { length: 255 }).notNull(), payload: json("payload").notNull(), occurredAt: timestamp("occurred_at").notNull() }, (table) => ({ typeIdx: index("events_type_idx").on(table.type) }));
export const executions = mysqlTable("executions", { id: varchar("id", { length: 36 }).primaryKey(), organizationId: varchar("organization_id", { length: 36 }).notNull(), workflowId: varchar("workflow_id", { length: 36 }).notNull(), status: varchar("status", { length: 32 }).notNull(), input: json("input").notNull(), output: json("output"), error: text("error"), startedAt: timestamp("started_at").notNull(), finishedAt: timestamp("finished_at") }, (table) => ({ workflowIdx: index("executions_workflow_idx").on(table.workflowId) }));
export const secrets = mysqlTable("secrets", { id: varchar("id", { length: 36 }).primaryKey(), organizationId: varchar("organization_id", { length: 36 }).notNull(), name: varchar("name", { length: 255 }).notNull(), encryptedValue: text("encrypted_value").notNull(), ...timestamps });
