import { boolean, jsonb, pgTable, text, timestamp, index } from "drizzle-orm/pg-core";

const timestamps = { createdAt: timestamp("created_at", { withTimezone: true }).notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull() };
export const organizations = pgTable("organizations", { id: text("id").primaryKey(), name: text("name").notNull(), slug: text("slug").notNull().unique(), ...timestamps });
export const users = pgTable("users", { id: text("id").primaryKey(), email: text("email").notNull().unique(), name: text("name").notNull(), ...timestamps });
export const memberships = pgTable("memberships", { id: text("id").primaryKey(), organizationId: text("organization_id").notNull().references(() => organizations.id), userId: text("user_id").notNull().references(() => users.id), role: text("role").notNull().default("viewer"), ...timestamps }, (table) => ({ organizationIdx: index("memberships_organization_idx").on(table.organizationId) }));
export const resources = pgTable("resources", { id: text("id").primaryKey(), organizationId: text("organization_id").notNull().references(() => organizations.id), name: text("name").notNull(), kind: text("kind").notNull(), config: jsonb("config").$type<Record<string, unknown>>().notNull(), ...timestamps });
export const workflows = pgTable("workflows", { id: text("id").primaryKey(), organizationId: text("organization_id").notNull().references(() => organizations.id), name: text("name").notNull(), description: text("description").notNull(), triggerEvent: text("trigger_event").notNull(), enabled: boolean("enabled").notNull().default(true), ...timestamps });
export const workflowNodes = pgTable("workflow_nodes", { id: text("id").primaryKey(), workflowId: text("workflow_id").notNull().references(() => workflows.id), kind: text("kind").notNull(), name: text("name").notNull(), capability: text("capability"), config: jsonb("config").$type<Record<string, unknown>>(), position: text("position").notNull().default("0") });
export const events = pgTable("events", { id: text("id").primaryKey(), organizationId: text("organization_id").notNull().references(() => organizations.id), type: text("type").notNull(), source: text("source").notNull(), payload: jsonb("payload").$type<Record<string, unknown>>().notNull(), occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull() }, (table) => ({ typeIdx: index("events_type_idx").on(table.type) }));
export const executions = pgTable("executions", { id: text("id").primaryKey(), organizationId: text("organization_id").notNull().references(() => organizations.id), workflowId: text("workflow_id").notNull().references(() => workflows.id), status: text("status").notNull(), input: jsonb("input").$type<Record<string, unknown>>().notNull(), output: jsonb("output").$type<Record<string, unknown>>(), error: text("error"), startedAt: timestamp("started_at", { withTimezone: true }).notNull(), finishedAt: timestamp("finished_at", { withTimezone: true }) }, (table) => ({ workflowIdx: index("executions_workflow_idx").on(table.workflowId) }));
export const secrets = pgTable("secrets", { id: text("id").primaryKey(), organizationId: text("organization_id").notNull().references(() => organizations.id), name: text("name").notNull(), encryptedValue: text("encrypted_value").notNull(), ...timestamps });
