import { integer, sqliteTable, text, index } from "drizzle-orm/sqlite-core";

const timestamps = { createdAt: text("created_at").notNull(), updatedAt: text("updated_at").notNull() };
export const organizations = sqliteTable("organizations", { id: text("id").primaryKey(), name: text("name").notNull(), slug: text("slug").notNull().unique(), ...timestamps });
export const users = sqliteTable("users", { id: text("id").primaryKey(), email: text("email").notNull().unique(), name: text("name").notNull(), ...timestamps });
export const memberships = sqliteTable("memberships", { id: text("id").primaryKey(), organizationId: text("organization_id").notNull().references(() => organizations.id), userId: text("user_id").notNull().references(() => users.id), role: text("role").notNull().default("viewer"), ...timestamps }, (table) => ({ organizationIdx: index("memberships_organization_idx").on(table.organizationId) }));
export const resources = sqliteTable("resources", { id: text("id").primaryKey(), organizationId: text("organization_id").notNull().references(() => organizations.id), name: text("name").notNull(), kind: text("kind").notNull(), config: text("config", { mode: "json" }).$type<Record<string, unknown>>().notNull(), ...timestamps });
export const workflows = sqliteTable("workflows", { id: text("id").primaryKey(), organizationId: text("organization_id").notNull().references(() => organizations.id), name: text("name").notNull(), description: text("description").notNull(), triggerEvent: text("trigger_event").notNull(), enabled: integer("enabled", { mode: "boolean" }).notNull().default(true), ...timestamps });
export const workflowNodes = sqliteTable("workflow_nodes", { id: text("id").primaryKey(), workflowId: text("workflow_id").notNull().references(() => workflows.id), kind: text("kind").notNull(), name: text("name").notNull(), capability: text("capability"), config: text("config", { mode: "json" }).$type<Record<string, unknown>>(), position: integer("position").notNull().default(0) });
export const events = sqliteTable("events", { id: text("id").primaryKey(), organizationId: text("organization_id").notNull().references(() => organizations.id), type: text("type").notNull(), source: text("source").notNull(), payload: text("payload", { mode: "json" }).$type<Record<string, unknown>>().notNull(), occurredAt: text("occurred_at").notNull() }, (table) => ({ typeIdx: index("events_type_idx").on(table.type) }));
export const executions = sqliteTable("executions", { id: text("id").primaryKey(), organizationId: text("organization_id").notNull().references(() => organizations.id), workflowId: text("workflow_id").notNull().references(() => workflows.id), status: text("status").notNull(), input: text("input", { mode: "json" }).$type<Record<string, unknown>>().notNull(), output: text("output", { mode: "json" }).$type<Record<string, unknown>>(), error: text("error"), startedAt: text("started_at").notNull(), finishedAt: text("finished_at") }, (table) => ({ workflowIdx: index("executions_workflow_idx").on(table.workflowId) }));
export const secrets = sqliteTable("secrets", { id: text("id").primaryKey(), organizationId: text("organization_id").notNull().references(() => organizations.id), name: text("name").notNull(), encryptedValue: text("encrypted_value").notNull(), ...timestamps });
